
  CREATE TABLE "PPNCARGO"."BILL_OF_LANDING" 
   (	"ID_BOL" NUMBER(10,0) NOT NULL ENABLE, 
	"PC_INDICATOR" VARCHAR2(255 CHAR), 
	"BOL_NATURE" VARCHAR2(255 CHAR), 
	"BOL_REFERENCE" VARCHAR2(255 CHAR), 
	"BOL_TYPE_CODE" VARCHAR2(255 CHAR), 
	"CONSIGNEE_ADDRESS" VARCHAR2(255 CHAR), 
	"CONSIGNEE_CODE" VARCHAR2(255 CHAR), 
	"CONSIGNEE_NAME" VARCHAR2(255 CHAR), 
	"CUSTOMS_CURRENCY" VARCHAR2(255 CHAR), 
	"CUSTOMS_VALUE" FLOAT(126), 
	"EXPORTER_ADDRESS" VARCHAR2(255 CHAR), 
	"EXPORTER_CODE" VARCHAR2(255 CHAR), 
	"EXPORTER_NAME" VARCHAR2(255 CHAR), 
	"FREIGHT_CURRENCY" VARCHAR2(255 CHAR), 
	"FREIGHT_VALUE" FLOAT(126), 
	"GOODS_DESCRIPTION" VARCHAR2(1000 CHAR), 
	"GROSS_MASS" FLOAT(126) NOT NULL ENABLE, 
	"ID_GENERAL" NUMBER(10,0) NOT NULL ENABLE, 
	"INFORMATION" VARCHAR2(255 CHAR), 
	"INSURANCE_CURRENCY" VARCHAR2(255 CHAR), 
	"INSURANCE_VALUE" FLOAT(126), 
	"LINE_NUMBER" NUMBER(*,0) NOT NULL ENABLE, 
	"LOCATION_CODE" VARCHAR2(255 CHAR), 
	"LOCATION_INFO" VARCHAR2(255 CHAR), 
	"MASTER_BOL_REF_NUMBER" VARCHAR2(255 CHAR), 
	"NOTIFY_ADDRESS" VARCHAR2(255 CHAR), 
	"NOTIFY_CODE" VARCHAR2(255 CHAR), 
	"NOTIFY_NAME" VARCHAR2(255 CHAR), 
	"NUM_OF_CTN_FOR_THIS_BOL" FLOAT(126) NOT NULL ENABLE, 
	"NUMBER_OF_PACKAGES" FLOAT(126) NOT NULL ENABLE, 
	"PACKAGE_TYPE_CODE" VARCHAR2(255 CHAR), 
	"PLACE_OF_LOADING_CODE" VARCHAR2(255 CHAR), 
	"PLACE_OF_UNLOADING_CODE" VARCHAR2(255 CHAR), 
	"SHIPPING_MARKS" VARCHAR2(1000 CHAR), 
	"TRANSPORT_CURRENCY" VARCHAR2(255 CHAR), 
	"TRANSPORT_VALUE" FLOAT(126), 
	"UNIQUE_CARRIER_REFERENCE" VARCHAR2(255 CHAR), 
	"VOLUME_IN_CUBIC_METERS" FLOAT(126) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_BOL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TS_CARGO_I_1"  ENABLE, 
	 CONSTRAINT "ID_GENERAL_GI" FOREIGN KEY ("ID_GENERAL")
	  REFERENCES "PPNCARGO"."GENERAL_INFO" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TS_CARGO_I_1" ;
 
