CREATE TABLE "PPNCARGO"."GENERAL_INFO" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CARRIER_ADDRESS" VARCHAR2(255 CHAR), 
	"CARRIER_CODE" VARCHAR2(255 CHAR), 
	"CARRIER_NAME" VARCHAR2(255 CHAR), 
	"CUSTOMS_OFFICE_CODE" VARCHAR2(255 CHAR), 
	"DATE_ARRIVAL" VARCHAR2(20 CHAR), 
	"DATE_DEPARTURE" VARCHAR2(20 CHAR), 
	"DATE_LAST_DISCHARGE" VARCHAR2(20 CHAR), 
	"DATE_OF_REGISTRATION" VARCHAR2(20 CHAR), 
	"IDENTITY_TRANSPORTER" VARCHAR2(255 CHAR), 
	"MASTER_INFORMATION" VARCHAR2(255 CHAR), 
	"MODE_TRANSPORT" VARCHAR2(255 CHAR), 
	"NATIONALITY_TRANSPORTER" VARCHAR2(255 CHAR), 
	"NUMERO_ESCALE" VARCHAR2(10 CHAR), 
	"PLACE_OF_DEPARTURE_CODE" VARCHAR2(255 CHAR), 
	"PLACE_OF_DESTINATION_CODE" VARCHAR2(255 CHAR), 
	"PLACE_OF_TRANSPORTER" VARCHAR2(255 CHAR), 
	"REGISTRATION_NUMBER" VARCHAR2(255 CHAR), 
	"SHIPPING_AGENT_CODE" VARCHAR2(255 CHAR), 
	"SHIPPING_AGENT_NAME" VARCHAR2(255 CHAR), 
	"TIME_ARRIVAL" VARCHAR2(255 CHAR), 
	"TONNAGE_GROSS_WEIGHT" FLOAT(126) NOT NULL ENABLE, 
	"TONNAGE_NET_WEIGHT" FLOAT(126) NOT NULL ENABLE, 
	"TOTAL_NUMBER_OF_BOLS" FLOAT(126), 
	"TOTAL_GROSS_MASS" FLOAT(126) NOT NULL ENABLE, 
	"TOTAL_NUMBER_OF_CONTAINERS" FLOAT(126) NOT NULL ENABLE, 
	"TOTAL_NUMBER_OF_PACKAGES" FLOAT(126) NOT NULL ENABLE, 
	"VOYAGE_NUMBER" VARCHAR2(20 BYTE), 
	"ID_ESCALE" NUMBER(10,0), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TS_CARGO_I_1"  ENABLE, 
	 CONSTRAINT "FKT0IWGOIV30UXUF4O32A6E49Y1" FOREIGN KEY ("ID_ESCALE")
	  REFERENCES "PPNCARGO"."ESCALE" ("ESCLEUNIK") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TS_CARGO_I_1" ;
 
