/*
 Navicat Premium Data Transfer

 Source Server         : data.db
 Source Server Type    : SQLite
 Source Server Version : 3026000
 Source Schema         : main

 Target Server Type    : SQLite
 Target Server Version : 3026000
 File Encoding         : 65001

 Date: 10/07/2019 11:00:31
*/

PRAGMA foreign_keys = false;

-- ----------------------------
-- Table structure for LOCALISATION
-- ----------------------------
DROP TABLE IF EXISTS "LOCALISATION";
CREATE TABLE "LOCALISATION" (
  "code" TEXT,
  "libelle" TEXT
);

-- ----------------------------
-- Records of LOCALISATION
-- ----------------------------
BEGIN;
INSERT INTO "LOCALISATION" VALUES ('PSA64', 'PARC AUTO');
INSERT INTO "LOCALISATION" VALUES ('PSP78', 'Terre Plein PANALPINA');
INSERT INTO "LOCALISATION" VALUES ('PSB41', 'MAGASIN LOT N°12 EX JBZ');
INSERT INTO "LOCALISATION" VALUES ('PSB42', 'MAGASIN LOT N°4 EX PANALPINA');
INSERT INTO "LOCALISATION" VALUES ('PSB44', 'MAGASIN MOLE 4');
INSERT INTO "LOCALISATION" VALUES ('PSB45', 'MAGASIN MOLE 3');
INSERT INTO "LOCALISATION" VALUES ('PSB46', 'MAGASIN M');
INSERT INTO "LOCALISATION" VALUES ('PSB47', 'MAGASIN B"');
INSERT INTO "LOCALISATION" VALUES ('PSB48', 'MAGASIN N°1 ORDINAIRE');
INSERT INTO "LOCALISATION" VALUES ('PSB49', 'MAGASIN F');
INSERT INTO "LOCALISATION" VALUES ('PSB50', 'MAGASIN O');
INSERT INTO "LOCALISATION" VALUES ('PSB51', 'MAGASIN MOLE 2');
INSERT INTO "LOCALISATION" VALUES ('PSB53', 'MAGASIN G1');
INSERT INTO "LOCALISATION" VALUES ('PSB52', 'MAGASIN I');
INSERT INTO "LOCALISATION" VALUES ('PSB54', 'MAGASIN  MOLE 1');
INSERT INTO "LOCALISATION" VALUES ('PSB55', 'MAGASIN L (CIMCONGO)');
INSERT INTO "LOCALISATION" VALUES ('PSB56', 'MAGASIN LOT N°7');
INSERT INTO "LOCALISATION" VALUES ('PSB57', 'MAGASIN N°2 TRAVEE 2B ORDINAIRE');
INSERT INTO "LOCALISATION" VALUES ('PSB58', 'MAGASIN LOT N°9 ORDINAIRE');
INSERT INTO "LOCALISATION" VALUES ('PSB59', 'MAGASIN LOT N° H5');
INSERT INTO "LOCALISATION" VALUES ('PSB60', 'MAGASIN N°3 SARIS');
INSERT INTO "LOCALISATION" VALUES ('PSB61', 'MAGASIN N°2 PETROLE');
INSERT INTO "LOCALISATION" VALUES ('PSB62', 'MAGASIN LOT N°9 PETROLIER');
INSERT INTO "LOCALISATION" VALUES ('PSB76', 'PARC SDV');
INSERT INTO "LOCALISATION" VALUES ('PSB84', 'MAGASIN G2');
INSERT INTO "LOCALISATION" VALUES ('PSC52', 'MAGASIN SOCOTRA');
INSERT INTO "LOCALISATION" VALUES ('PSB63', 'MAGASIN DEGROUPAGE H 8(SDV)');
INSERT INTO "LOCALISATION" VALUES ('PSD73', 'MAGASIN FACE CTIC LOT N°1');
INSERT INTO "LOCALISATION" VALUES ('PSD74', 'MAGASIN Ex-JBZ LOT N°3');
INSERT INTO "LOCALISATION" VALUES ('SCO03', 'MAGASIN  LOT 6 N°2');
INSERT INTO "LOCALISATION" VALUES ('PSD75', 'MAGASIN Ex-PANALPINA B');
INSERT INTO "LOCALISATION" VALUES ('SCO022', 'MAGASIN SOCOTRANS LOT 22');
INSERT INTO "LOCALISATION" VALUES ('PST65', 'MAGASIN MOLE 5');
INSERT INTO "LOCALISATION" VALUES ('SC011', 'MAGASIN SOCOTRANS EX SANCO');
INSERT INTO "LOCALISATION" VALUES ('PST66', 'MAGASIN MOLE 6');
INSERT INTO "LOCALISATION" VALUES ('SC005', 'MAGASIN SOCOTRANS LOT 20');
INSERT INTO "LOCALISATION" VALUES ('PST67', 'MAGASIN N');
INSERT INTO "LOCALISATION" VALUES ('SC010', 'MAGASIN SOCOTRANS LOT 13');
INSERT INTO "LOCALISATION" VALUES ('PST68', 'MAGASIN L');
INSERT INTO "LOCALISATION" VALUES ('SC006', 'MAGASIN SOCOTRANS  ENTRE RAIL');
INSERT INTO "LOCALISATION" VALUES ('PST69', 'MAGASIN K');
INSERT INTO "LOCALISATION" VALUES ('SC007', 'MAGASIN SOCOTRANS LOT 3');
INSERT INTO "LOCALISATION" VALUES ('PST70', 'MAGASIN KBIS');
INSERT INTO "LOCALISATION" VALUES ('SC008', 'MAGASIN SOCOTRANS LOT 1');
INSERT INTO "LOCALISATION" VALUES ('PST71', 'MAGASIN EA');
INSERT INTO "LOCALISATION" VALUES ('SC009', 'MAGASIN SOSCOTRANS MOLE 7');
INSERT INTO "LOCALISATION" VALUES ('PST72', 'MAGASIN DEGROUPAGE ONPT(SOCOTRANS)');
INSERT INTO "LOCALISATION" VALUES ('PST77', 'PARC SOCOTRANS');
INSERT INTO "LOCALISATION" VALUES ('PST81', 'MAGASIN Lbis');
INSERT INTO "LOCALISATION" VALUES ('PST82', 'MAGASIN Lter');
INSERT INTO "LOCALISATION" VALUES ('PST83', 'MAGASIN EB');
INSERT INTO "LOCALISATION" VALUES ('PAE16', 'MAGASIN EQUAFLIGHT AEROPORT');
INSERT INTO "LOCALISATION" VALUES ('PAD18', 'MAGASIN DHL AEROPORT');
INSERT INTO "LOCALISATION" VALUES ('PAG13', 'MAGASIN GETMA AEROPORT');
INSERT INTO "LOCALISATION" VALUES ('PAH14', 'MAGASIN CONGO HANDLING AEROPORT');
INSERT INTO "LOCALISATION" VALUES ('PAL15', 'MAGASIN LINA CONGO AEROPORT');
INSERT INTO "LOCALISATION" VALUES ('PAP12', 'MAGASIN PANALPINA AEROPORT');
INSERT INTO "LOCALISATION" VALUES ('PAT17', 'MAGASIN SOCOTRA AEROPORT');
INSERT INTO "LOCALISATION" VALUES ('PAV11', 'MAGASIN SDV AEROPORT');
INSERT INTO "LOCALISATION" VALUES ('PBA19', 'MAGASIN BAGAGES ACCOMPAGNES');
INSERT INTO "LOCALISATION" VALUES ('ESSAI', 'Magasin test');
INSERT INTO "LOCALISATION" VALUES ('PBC78', 'BOSCONGO (Zone Industrielle)');
INSERT INTO "LOCALISATION" VALUES ('PEC79', 'Zone Industri BASE ELF-TOTAL-FINA');
INSERT INTO "LOCALISATION" VALUES ('PSS80', 'INTELS (BASE INDUSTRIELLE)');
INSERT INTO "LOCALISATION" VALUES ('PSB43', 'MAGASIN H');
INSERT INTO "LOCALISATION" VALUES ('PSB85', 'TERRE PLEIN SDV');
INSERT INTO "LOCALISATION" VALUES ('PSB77', 'PARC CONGO TERMINAL');
INSERT INTO "LOCALISATION" VALUES ('RADE001', 'RADE');
INSERT INTO "LOCALISATION" VALUES ('PGET1', 'YARD GETMA1');
INSERT INTO "LOCALISATION" VALUES ('PGET27', 'YARD GETMA2');
INSERT INTO "LOCALISATION" VALUES ('PGET3', 'YARD GETMA3');
INSERT INTO "LOCALISATION" VALUES ('PGET4', 'YARD GETMA4');
INSERT INTO "LOCALISATION" VALUES ('HTM', 'HAUTE MER');
INSERT INTO "LOCALISATION" VALUES ('PST84', 'MAGASIN LOT 62 BIS');
INSERT INTO "LOCALISATION" VALUES ('PST85', 'LOT 6 N°1');
INSERT INTO "LOCALISATION" VALUES ('PST86', 'MAGASIN LOT 6 N°1');
INSERT INTO "LOCALISATION" VALUES ('PST95', 'TERRE PLEIN SOCOTRANS-TRANSCAP');
INSERT INTO "LOCALISATION" VALUES ('SC001', 'MAGASIN SOCOTRANS LOT2 BIS');
INSERT INTO "LOCALISATION" VALUES ('SC002', 'MAGASIN SOCOTRANS LOT 6 N°1');
INSERT INTO "LOCALISATION" VALUES ('SC0022', 'MAGASIN SOCOTRANS LOT22');
INSERT INTO "LOCALISATION" VALUES ('SC003', 'MAGASIN SOCOTRANS LOT 6 N°2');
INSERT INTO "LOCALISATION" VALUES ('SSPALAN', 'MAGASIN SOUS PALAN');
INSERT INTO "LOCALISATION" VALUES ('SCO04', 'MAGASIN SOCOTRANS LOT 18');
INSERT INTO "LOCALISATION" VALUES ('OC01', 'MAGASIN OCEAN EXPRESS');
INSERT INTO "LOCALISATION" VALUES ('SCLOG', 'DEPOT SCLOG');
INSERT INTO "LOCALISATION" VALUES ('BAT04', 'SOCOTRA AEROPORT');
INSERT INTO "LOCALISATION" VALUES ('PST96', 'PARC ZONE EST( POR SARA )');
INSERT INTO "LOCALISATION" VALUES ('TPIFO', 'TERRE PLEIN IFO');
INSERT INTO "LOCALISATION" VALUES ('TPCIB', 'TERRE PLEIN CIB"');
COMMIT;

PRAGMA foreign_keys = true;
